handlers:
  udp:
    port: 53
    threadsPoolSize: 10

upstreams:
  values:
    -
      address: 8.8.8.8
      port: 53
    -
      address: 1.1.1.1
      port: 53

records:
  values:
    -
      domain: fadeev.com
      type: A
      values:
        - 127.0.0.1
        - 127.0.0.2
    - domain: fadeev.com
      type: AAAA
      values:
        - 2001:0db8:85a3:0000:0000:8a2e:0370:7334
        - 2001:0db8:85a3:0000:0000:8a2e:0370:7334